deployment:
  tasks:
    - export DEPLOY_PATH=/home/portally/evadesopm.site
    - /bin/cp -R assets backend database frontend img OPM index.html .htaccess $DEPLOY_PATH
    - echo "Despliegue completado en $(date)" >> $DEPLOY_PATH/deploy.log
