import { useEffect, useRef, useState } from 'react'
import { CalendarDays, Download, Search, Upload, UserPlus, UsersRound } from 'lucide-react'
import { api } from '../api.js'
import { useShift } from '../shift.jsx'
import TopBar from '../components/TopBar.jsx'
import { T, turnoText, useLang } from '../i18n.js'

const today = () => new Date().toISOString().slice(0, 10)
const EMPTY = { opm_id: '', funcion_1: '', funcion_2: '', zona_1: '', puesto: '', nave: '', nave_2: '' }

export default function Asignaciones() {
  const { shift } = useShift(); const [lang] = useLang(); const t = T[lang]
  const [date, setDate] = useState(shift?.date || today()); const [turno, setTurno] = useState(shift?.turno || 'dia')
  const [assignments, setAssignments] = useState([]); const [loading, setLoading] = useState(true); const [importing, setImporting] = useState(false); const [downloading, setDownloading] = useState(false)
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [showIndividual, setShowIndividual] = useState(false); const [opms, setOpms] = useState([]); const [individual, setIndividual] = useState(EMPTY); const [savingIndividual, setSavingIndividual] = useState(false)
  const fileRef = useRef(null)
  async function load() { setLoading(true); setError(''); try { const data = await api.assignments(date, turno); setAssignments(data.assignments || []) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [date, turno])
  useEffect(() => { api.opms().then((data) => setOpms((data.opms || []).filter((opm) => opm.active))).catch(() => {}) }, [])
  async function importFile(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setImporting(true); setError(''); setMessage(''); try { const result = await api.importAssignments(file, turno, date); const errors = result.errors?.length ? ` ${t.asignacionFilasError(result.errors.length)}.` : ''; setMessage(t.asignacionImportada(result.imported) + errors); if (result.dates?.includes(date)) await load() } catch (err) { setError(err.message) } finally { setImporting(false) } }
  async function downloadTemplate() { setDownloading(true); setError(''); try { await api.downloadAssignmentsTemplate() } catch (err) { setError(err.message) } finally { setDownloading(false) } }
  async function saveIndividual(event) { event.preventDefault(); setSavingIndividual(true); setError(''); setMessage(''); try { await api.createAssignmentIndividual({ ...individual, date, turno }); setMessage('Colaborador asignado correctamente al turno.'); setIndividual(EMPTY); setShowIndividual(false); await load() } catch (err) { setError(err.message) } finally { setSavingIndividual(false) } }
  return <><TopBar title={t.asignacionesTitulo} to="/admin" /><main className="content">{error && <div className="error" role="alert">{error}</div>}{message && <div className="success">{message}</div>}<section className="card" aria-labelledby="assignment-import-title"><h3 id="assignment-import-title">{t.cargarAsignaciones}</h3><p className="muted assignment-copy">{t.cargarAsignacionesD}</p><div className="row assignment-picker"><div><label htmlFor="assignment-date">{t.fecha}</label><input id="assignment-date" className="input" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div><div><label htmlFor="assignment-turno">{t.turnoTrabajo}</label><select id="assignment-turno" className="input" value={turno} onChange={(event) => setTurno(event.target.value)}><option value="dia">{t.turnoDia}</option><option value="noche">{t.turnoNoche}</option></select></div></div><div className="row assignment-actions"><button className="btn" disabled={importing} onClick={() => fileRef.current?.click()}><Upload size={16} /> {importing ? t.importando : t.importarAsignaciones}</button><button className="btn secondary" onClick={() => setShowIndividual((value) => !value)}><UserPlus size={16} /> {showIndividual ? 'Ocultar registro' : 'Registro individual'}</button><button className="btn secondary" disabled={downloading} onClick={downloadTemplate}><Download size={16} /> {downloading ? t.descargando : t.exportarPlantilla}</button></div><input ref={fileRef} type="file" accept=".xlsx" hidden onChange={importFile} /></section>{showIndividual && <IndividualOpmForm form={individual} setForm={setIndividual} opms={opms} saving={savingIndividual} onSubmit={saveIndividual} />}<section className="assignment-list" aria-labelledby="assignment-list-title"><div className="assignment-list-heading"><div><h2 id="assignment-list-title">{t.asignadosTurno}</h2><p>{date} · {turnoText(turno, lang)}</p></div><span className="chip"><UsersRound size={14} /> {assignments.length}</span></div>{loading ? <div className="empty">{t.cargando}</div> : assignments.length === 0 ? <div className="assignment-empty"><CalendarDays size={25} /><div><strong>{t.sinAsignacionesTitulo}</strong><span>{t.sinAsignacionesAdmin}</span></div></div> : assignments.map((item) => <article className="assignment-row" key={item.id}><div className="assignment-row-main"><strong>{item.opm_name}</strong><span>{item.opm_code} · {item.puesto || t.sinPuesto}</span></div><div className="assignment-row-detail"><span>{item.funcion_1 || t.sinFuncion}</span>{item.funcion_2 && <span>{item.funcion_2}</span>}</div><div className="assignment-row-meta">{item.zona_1 || t.sinZona}{item.nave ? ` · ${item.nave}` : ''}{item.nave_2 ? ` · ${item.nave_2}` : ''}</div></article>)}</section></main></>
}

function IndividualOpmForm({ form, setForm, opms, saving, onSubmit }) {
  const selected = opms.find((opm) => String(opm.id) === String(form.opm_id))
  const update = (field, value) => setForm({ ...form, [field]: value })
  function choose(opmId) {
    const opm = opms.find((item) => String(item.id) === String(opmId))
    setForm({ ...form, opm_id: opmId, puesto: opm?.puesto || '' })
  }
  return <form className="card" onSubmit={onSubmit}><h3>Asignar colaborador individualmente</h3><p className="muted assignment-copy">La asignación se guardará para la fecha y turno seleccionados.</p><label>Colaborador</label><SearchablePicker items={opms} value={form.opm_id} onSelect={choose} labelOf={(opm) => opm.full_name} searchOf={(opm) => `${opm.code} ${opm.full_name}`} placeholder="Escriba código o nombre del colaborador" />{selected && <div className="radio-form-grid assignment-person-data"><div><label>Código</label><input className="input" readOnly value={selected.code || ''} /></div><div><label>Cargo</label><input className="input" readOnly value={selected.puesto || ''} /></div></div>}<AssignmentFields form={form} update={update} hidePuesto /><button className="btn individual-assignment-submit" disabled={saving}>{saving ? 'Guardando…' : 'Agregar colaborador al turno'}</button></form>
}

export function SearchablePicker({ items, value, onSelect, labelOf, searchOf, placeholder, isDisabled = () => false }) { const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const selected = items.find((item) => String(item.id) === String(value)); const text = open ? query : (selected ? labelOf(selected) : query); const matches = query.trim() ? items.filter((item) => searchOf(item).toLowerCase().includes(query.trim().toLowerCase())).slice(0, 30) : []; function select(item) { if (isDisabled(item)) return; onSelect(item.id); setQuery(labelOf(item)); setOpen(false) } return <div className="search-picker"><div className="search-picker-input"><Search size={16} /><input className="input" value={text} onFocus={() => { setQuery(selected ? labelOf(selected) : query); setOpen(true) }} onChange={(event) => { setQuery(event.target.value); onSelect(''); setOpen(true) }} onBlur={() => setTimeout(() => setOpen(false), 120)} placeholder={placeholder} autoComplete="off" /></div>{open && <div className="search-picker-menu">{!query.trim() ? <div className="search-picker-empty">Escriba para buscar.</div> : matches.length ? matches.map((item) => <button type="button" key={item.id} disabled={isDisabled(item)} onMouseDown={(event) => { event.preventDefault(); select(item) }}>{labelOf(item)}</button>) : <div className="search-picker-empty">No se encontraron coincidencias.</div>}</div>}</div> }

export function AssignmentFields({ form, update, hidePuesto = false }) { return <div className="radio-form-grid"><div><label>Función 1</label><input className="input" value={form.funcion_1} onChange={(event) => update('funcion_1', event.target.value)} /></div><div><label>Función 2</label><input className="input" value={form.funcion_2} onChange={(event) => update('funcion_2', event.target.value)} /></div><div><label>Zona 1</label><input className="input" value={form.zona_1} onChange={(event) => update('zona_1', event.target.value)} /></div>{!hidePuesto && <div><label>Puesto</label><input className="input" value={form.puesto} onChange={(event) => update('puesto', event.target.value)} /></div>}<div><label>Nave</label><input className="input" value={form.nave} onChange={(event) => update('nave', event.target.value)} /></div><div><label>Nave 2</label><input className="input" value={form.nave_2} onChange={(event) => update('nave_2', event.target.value)} /></div></div> }
