import { useEffect, useRef, useState } from 'react'
import { CalendarDays, Download, Search, Upload, UserPlus, UsersRound } from 'lucide-react'
import { api } from '../api.js'
import { useShift } from '../shift.jsx'
import TopBar from '../components/TopBar.jsx'
import { T, turnoText, useLang } from '../i18n.js'

const today = () => new Date().toISOString().slice(0, 10)
const EMPTY = { person_key: '', funcion_1: '', funcion_2: '', zona_1: '', puesto: '', nave: '', nave_2: '' }

export default function Asignaciones() {
  const { shift } = useShift(); const [lang] = useLang(); const t = T[lang]
  const [date, setDate] = useState(shift?.date || today()); const [turno, setTurno] = useState(shift?.turno || 'dia')
  const [assignments, setAssignments] = useState([]); const [people, setPeople] = useState([]); const [loading, setLoading] = useState(true)
  const [importType, setImportType] = useState('opms'); const [importing, setImporting] = useState(false); const [downloading, setDownloading] = useState(false)
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [showIndividual, setShowIndividual] = useState(false); const [individual, setIndividual] = useState(EMPTY); const [saving, setSaving] = useState(false)
  const fileRef = useRef(null)
  async function load() { setLoading(true); setError(''); try { const [opmData, supervisorData] = await Promise.all([api.assignments(date, turno), api.supervisorAssignments(date, turno)]); setAssignments([...(opmData.assignments || []).map((row) => ({ ...row, person_type: 'opm', full_name: row.opm_name, code: row.opm_code })), ...(supervisorData.assignments || []).map((row) => ({ ...row, person_type: row.role, full_name: row.full_name, code: row.employee_number || '' }))].sort((a, b) => a.full_name.localeCompare(b.full_name))) } catch (err) { setError(err.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [date, turno])
  useEffect(() => { Promise.all([api.opms(), api.users()]).then(([opmData, usersData]) => setPeople([...(opmData.opms || []).filter((person) => person.active).map((person) => ({ ...person, person_type: 'opm', person_key: `opm:${person.id}`, code: person.code })), ...(usersData.users || []).filter((person) => person.active && ['supervisor', 'coordinator'].includes(person.role)).map((person) => ({ ...person, person_type: person.role, person_key: `${person.role}:${person.id}`, code: person.employee_number }))])).catch(() => {}) }, [])
  async function importFile(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; setImporting(true); setError(''); setMessage(''); try { const result = importType === 'opms' ? await api.importAssignments(file, turno, date) : await api.importSupervisorAssignments(file, turno, date); const omitted = result.errors?.length ? ` Se omitieron ${result.errors.length} filas.` : ''; setMessage(`Se importaron ${result.imported} asignaciones.${omitted}`); await load() } catch (err) { setError(err.message) } finally { setImporting(false) } }
  async function downloadTemplate() { setDownloading(true); setError(''); try { importType === 'opms' ? await api.downloadAssignmentsTemplate() : await api.downloadSupervisorAssignmentsTemplate() } catch (err) { setError(err.message) } finally { setDownloading(false) } }
  async function saveIndividual(event) { event.preventDefault(); const person = people.find((item) => item.person_key === individual.person_key); if (!person) return; setSaving(true); setError(''); setMessage(''); try { const payload = { ...individual, date, turno, puesto: individual.puesto || person.puesto || '' }; person.person_type === 'opm' ? await api.createAssignmentIndividual({ ...payload, opm_id: person.id }) : await api.createSupervisorAssignmentIndividual({ ...payload, user_id: person.id }); setMessage('Asignación registrada correctamente.'); setIndividual(EMPTY); setShowIndividual(false); await load() } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <><TopBar title={t.asignacionesTitulo} to="/admin" /><main className="content">{error && <div className="error" role="alert">{error}</div>}{message && <div className="success">{message}</div>}<section className="card"><h3>{t.cargarAsignaciones}</h3><p className="muted assignment-copy">Registre las funciones de todo el personal. Seleccione el cargo antes de importar su plantilla.</p><div className="row assignment-picker"><div><label>Fecha</label><input className="input" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div><div><label>Turno de trabajo</label><select className="input" value={turno} onChange={(event) => setTurno(event.target.value)}><option value="dia">{t.turnoDia}</option><option value="noche">{t.turnoNoche}</option></select></div></div><label>Personal de la plantilla</label><select className="input" value={importType} onChange={(event) => setImportType(event.target.value)}><option value="opms">Colaboradores / OPM / Tally</option><option value="supervisors">Supervisores y coordinadores</option></select><div className="row assignment-actions"><button className="btn" disabled={importing} onClick={() => fileRef.current?.click()}><Upload size={16} /> {importing ? 'Importando...' : 'Importar Excel'}</button><button className="btn secondary" onClick={() => setShowIndividual((value) => !value)}><UserPlus size={16} /> {showIndividual ? 'Ocultar registro' : 'Registro individual'}</button><button className="btn secondary" disabled={downloading} onClick={downloadTemplate}><Download size={16} /> {downloading ? 'Descargando...' : 'Exportar plantilla'}</button></div><input ref={fileRef} type="file" accept=".xlsx" hidden onChange={importFile} /></section>{showIndividual && <IndividualForm form={individual} setForm={setIndividual} people={people} saving={saving} onSubmit={saveIndividual} />}<section className="assignment-list"><div className="assignment-list-heading"><div><h2>Personal asignado</h2><p>{date} · {turnoText(turno, lang)}</p></div><span className="chip"><UsersRound size={14} /> {assignments.length}</span></div>{loading ? <div className="empty">{t.cargando}</div> : assignments.length === 0 ? <div className="assignment-empty"><CalendarDays size={25} /><div><strong>No hay asignaciones</strong><span>Importe una plantilla o registre una asignación individual.</span></div></div> : assignments.map((row) => <article className="assignment-row" key={`${row.person_type}:${row.id}`}><div className="assignment-row-main"><strong>{row.full_name}</strong><span>{row.code ? `${row.code} · ` : ''}{row.puesto || roleLabel(row)}</span></div><div className="assignment-row-detail"><strong>{row.funcion_1 || t.sinFuncion}</strong><span>{[row.zona_1, row.nave].filter(Boolean).join(' · ') || 'Sin zona o nave'}</span></div></article>)}</section></main></>
}

function IndividualForm({ form, setForm, people, saving, onSubmit }) { const selected = people.find((item) => item.person_key === form.person_key); const update = (field, value) => setForm({ ...form, [field]: value }); function choose(personKey) { const person = people.find((item) => item.person_key === personKey); setForm({ ...form, person_key: personKey, puesto: person?.puesto || '' }) } return <form className="card" onSubmit={onSubmit}><h3>Asignar personal individualmente</h3><p className="muted assignment-copy">Busque cualquier colaborador, supervisor o coordinador activo.</p><label>Colaborador</label><SearchablePicker items={people} value={form.person_key} onSelect={choose} labelOf={(person) => `${person.full_name} · ${person.puesto || roleLabel(person)}`} searchOf={(person) => `${person.code || ''} ${person.full_name} ${person.puesto || ''} ${roleLabel(person)}`} placeholder="Escriba código, nombre o cargo" />{selected && <div className="radio-form-grid assignment-person-data"><div><label>Código</label><input className="input" readOnly value={selected.code || ''} /></div><div><label>Cargo</label><input className="input" readOnly value={selected.puesto || roleLabel(selected)} /></div></div>}<AssignmentFields form={form} update={update} hidePuesto /><button className="btn individual-assignment-submit" disabled={saving || !selected}>{saving ? 'Guardando...' : 'Agregar al turno'}</button></form> }
export function SearchablePicker({ items, value, onSelect, labelOf, searchOf, placeholder }) { const [query, setQuery] = useState(''); const [open, setOpen] = useState(false); const selected = items.find((item) => String(item.person_key || item.id) === String(value)); const text = open ? query : (selected ? labelOf(selected) : query); const matches = query.trim() ? items.filter((item) => searchOf(item).toLowerCase().includes(query.trim().toLowerCase())).slice(0, 30) : []; function select(item) { onSelect(item.person_key || item.id); setQuery(labelOf(item)); setOpen(false) } return <div className="search-picker"><div className="search-picker-input"><Search size={16} /><input className="input" value={text} onFocus={() => { setQuery(selected ? labelOf(selected) : query); setOpen(true) }} onChange={(event) => { setQuery(event.target.value); onSelect(''); setOpen(true) }} onBlur={() => setTimeout(() => setOpen(false), 120)} placeholder={placeholder} autoComplete="off" /></div>{open && <div className="search-picker-menu">{!query.trim() ? <div className="search-picker-empty">Escriba para buscar.</div> : matches.length ? matches.map((item) => <button type="button" key={item.person_key || item.id} onMouseDown={(event) => { event.preventDefault(); select(item) }}>{labelOf(item)}</button>) : <div className="search-picker-empty">No se encontraron coincidencias.</div>}</div>}</div> }
export function AssignmentFields({ form, update, hidePuesto = false }) { return <div className="radio-form-grid"><div><label>Función 1</label><input className="input" value={form.funcion_1} onChange={(event) => update('funcion_1', event.target.value)} /></div><div><label>Función 2</label><input className="input" value={form.funcion_2} onChange={(event) => update('funcion_2', event.target.value)} /></div><div><label>Zona 1</label><input className="input" value={form.zona_1} onChange={(event) => update('zona_1', event.target.value)} /></div>{!hidePuesto && <div><label>Puesto</label><input className="input" value={form.puesto} onChange={(event) => update('puesto', event.target.value)} /></div>}<div><label>Nave</label><input className="input" value={form.nave} onChange={(event) => update('nave', event.target.value)} /></div><div><label>Nave 2</label><input className="input" value={form.nave_2} onChange={(event) => update('nave_2', event.target.value)} /></div></div> }
const roleLabel = (person) => person.person_type === 'coordinator' ? 'Coordinador' : person.person_type === 'supervisor' ? 'Supervisor' : ''
